# Docker Compose multi-stage per stl2glb
# Stage 1: Builder con vcpkg
# Stage 2: Runtime minimale

volumes:
  vcpkg_cache:
    driver: local
    driver_opts:
      type: none
      device: /home/vcpkg
      o: bind

networks:
  stl2glb-network:
    driver: bridge

services:
  # Stage 1: Builder
  builder:
    image: alpine:3.19
    container_name: stl2glb_builder
    volumes:
      - ./:/project
      - vcpkg_cache:/vcpkg:ro
    working_dir: /project
    command: >
      sh -c "
      echo '🔧 Installazione build tools...' &&
      apk add --no-cache build-base cmake ninja linux-headers &&
      echo '🔍 Verifica vcpkg...' &&
      ls -la /vcpkg/ &&
      if [ ! -f '/vcpkg/vcpkg' ]; then
        echo '❌ vcpkg non trovato in /home/vcpkg';
        echo '🔧 Esegui prima: ./setup-vcpkg.sh';
        exit 1;
      fi &&
      if [ ! -d '/vcpkg/installed/x64-linux' ]; then
        echo '❌ dipendenze vcpkg x64-linux non installate';
        echo '📦 Directory installed disponibili:';
        ls -la /vcpkg/installed/ 2>/dev/null || echo 'Directory installed non trovata';
        exit 1;
      fi &&
      echo '🔍 Controllo librerie debug problematiche...' &&
      if [ -d '/vcpkg/installed/x64-linux/debug' ]; then
        echo '⚠️  Librerie debug trovate - potrebbero causare problemi';
        echo '📋 Contenuto debug:';
        ls -la /vcpkg/installed/x64-linux/debug/lib/ | head -3 || true;
      fi &&
      echo '✅ vcpkg verificato' &&
      echo '🔨 Fix per Linux se necessario...' &&
      if [ -f 'src/STLParser.cpp' ]; then
        grep -q '#include <cmath>' src/STLParser.cpp ||
        sed -i '/#include <atomic>/a #include <cmath>' src/STLParser.cpp;
      fi &&
      echo '🏗️  Build con vcpkg...' &&
      echo '🔍 Debug vcpkg paths:' &&
      echo 'VCPKG_INSTALLED_DIR:' && ls -la /vcpkg/installed/x64-linux/lib/ | head -5 &&
      echo '🧹 Pulizia cache CMake...' &&
      rm -rf build/ &&
      echo '🔧 Impostazione variabili vcpkg...' &&
      export VCPKG_ROOT=/vcpkg &&
      export VCPKG_DEFAULT_TRIPLET=x64-linux &&
      cmake -B build -S . -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_INSTALLED_DIR=/vcpkg/installed -DVCPKG_MANIFEST_MODE=OFF -DVCPKG_APPLOCAL_DEPS=OFF -GNinja &&
      cmake --build build --config MinSizeRel --parallel \$(nproc) &&
      strip build/stl2glb_exec &&
      echo '✅ Build completato'
      "
    networks:
      - stl2glb-network

  # Stage 2: Runtime minimale
  app:
    image: alpine:3.19
    container_name: stl2glb_tiny
    depends_on:
      builder:
        condition: service_completed_successfully
    volumes:
      - ./:/project:ro
    working_dir: /project
    command: >
      sh -c "
      echo '🔧 Installazione runtime libraries...' &&
      apk add --no-cache libstdc++ libgcc openssl ca-certificates wget &&
      adduser -D -u 1000 appuser &&
      echo '🔍 Verifica eseguibile...' &&
      if [ ! -f 'build/stl2glb_exec' ]; then
        echo '❌ Eseguibile non trovato. Builder fallito?';
        exit 1;
      fi &&
      echo '✅ Eseguibile trovato' &&
      echo '🚀 Avvio applicazione...' &&
      su appuser -c './build/stl2glb_exec'
      "
    ports:
      - "9002:8080"
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - MALLOC_ARENA_MAX=1
      - GOMAXPROCS=1

    # DNS ottimizzato
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8

    # Host esterni
    extra_hosts:
      - "minio:217.160.248.228"
      - "minio.aredegalli.it:217.160.248.228"

    # Risorse limitate per VPS
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
          pids: 50
        reservations:
          cpus: '0.1'
          memory: 64M

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 20s

    # Logging ottimizzato
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
        compress: "true"

    # Tuning di rete
    sysctls:
      - net.core.somaxconn=128
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=600

    # Tmpfs per file temporanei
    tmpfs:
      - /tmp:size=50M,noexec,nosuid,nodev

    networks:
      - stl2glb-network