version: "3.8"

networks:
  stl2glb-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stl2glb_app

    ports:
      - "9002:8080"

    restart: unless-stopped

    env_file:
      - .env

    # Host fissi per evitare lookup DNS
    extra_hosts:
      - "minio:217.160.248.228"
      - "minio.aredegalli.it:217.160.248.228"

    # Risorse ridotte per VPS
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50M

    # Logging ottimizzato
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

    networks:
      - stl2glb-network

# Configurazione globale
x-common-variables: &common-variables
  TZ: UTC
  MALLOC_ARENA_MAX: 1