# Docker Compose ottimizzato per VPS con vcpkg dall'host

services:
  # App ultra-minimale per VPS
  app:
    build:
      context: .
      dockerfile: Dockerfile-tiny
      args:
        - VCPKG_ROOT=/opt/vcpkg
      # Per montare vcpkg durante il build, usa il target specifico
      target: builder

    # Immagine finale ottimizzata
    image: stl2glb:tiny
    container_name: stl2glb_tiny

    # Configurazione minimale
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    ports:
      - "9002:8080"

    env_file:
      - .env

    environment:
      - MALLOC_ARENA_MAX=1
      - GOMAXPROCS=1

    # DNS cache locale
    dns:
      - 127.0.0.1
      - 1.1.1.1

    # Host MinIO
    extra_hosts:
      - "minio:217.160.248.228"
      - "minio.aredegalli.it:217.160.248.228"

    # Risorse ultra-limitate per VPS economiche
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
          pids: 50
        reservations:
          cpus: '0.1'
          memory: 64M

    # Health check corretto
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 20s

    # Logging minimale
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
        compress: "true"

    # Sysctls per performance su risorse limitate
    sysctls:
      - net.core.somaxconn=128
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=600

    # Tmpfs minimale
    tmpfs:
      - /tmp:size=50M,noexec,nosuid,nodev