# Docker Compose per stl2glb - RICHIEDE setup vcpkg
# PREREQUISITO: Eseguire prima ./setup-vcpkg.sh

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-tiny
      # Abilita BuildKit per il mount bind
      platforms:
        - linux/amd64

    image: stl2glb:tiny
    container_name: stl2glb_tiny

    # Configurazione sicurezza
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    ports:
      - "9002:8080"

    env_file:
      - .env

    environment:
      - MALLOC_ARENA_MAX=1
      - GOMAXPROCS=1

    # DNS ottimizzato
    dns:
      - 127.0.0.1
      - 1.1.1.1

    # Host esterni
    extra_hosts:
      - "minio:217.160.248.228"
      - "minio.aredegalli.it:217.160.248.228"

    # Risorse limitate per VPS
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
          pids: 50
        reservations:
          cpus: '0.1'
          memory: 64M

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 20s

    # Logging ottimizzato
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
        compress: "true"

    # Tuning di rete
    sysctls:
      - net.core.somaxconn=128
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=600

    # Tmpfs per file temporanei
    tmpfs:
      - /tmp:size=50M,noexec,nosuid,nodev